### ISSUE TITLE
When executing the evaluatation code , it reported the following error

### ISSUE THREAD

**Issue by chriscpy** [SHI-Labs/Rethinking-Text-Segmentation#9]
Traceback (most recent call last):
  File "main.py", line 223, in <module>
    join=True)
  File "/home/ma-user/anaconda3/envs/Pytorch-1.4.0/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ma-user/anaconda3/envs/Pytorch-1.4.0/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/home/ma-user/anaconda3/envs/Pytorch-1.4.0/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ma-user/anaconda3/envs/Pytorch-1.4.0/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/home/ma-user/work/Rethinking-Text-Segmentation-main/train_utils.py", line 94, in __call__
    stage_para = stage(**para)
  File "/home/ma-user/work/Rethinking-Text-Segmentation-main/eval_utils.py", line 392, in __call__
    class_n=cfg.DATA.EFFECTIVE_CLASS_NUM)
  File "/home/ma-user/work/Rethinking-Text-Segmentation-main/lib/evaluate_service.py", line 23, in wrapper
    rv = func(self, *args, **kwargs)
  File "/home/ma-user/work/Rethinking-Text-Segmentation-main/lib/evaluate_service.py", line 238, in bw_iandu
    i, u = nputils.iandu_auto(class_n)(p, g, m)
  File "/home/ma-user/work/Rethinking-Text-Segmentation-main/lib/nputils.py", line 274, in __call__
    raise ValueError
ValueError

**Comment by xingqian2018** [comment]
Looks like your predicted result has different dimensionality comparing with the group truth:
See the following code

        x_shape = list(x.shape)
        gt_shape = list(gt.shape)

        if x_shape == gt_shape:
            return iandu_normal(self.max_index)(x, gt, m)
        elif x_shape == gt_shape[0:1]+gt_shape[2:]:
            return iandu_iv(self.max_index)(x, gt, m)
        else:
            raise ValueError
